name: Check, build, and push Docker image

on:
  workflow_call:

permissions:
  contents: read

jobs:
  check:
    name: Check project
    uses: ./.github/workflows/check.yml
    secrets: inherit

  docker:
    name: Build and push Docker image
    needs: check
    uses: ./.github/workflows/push-docker-hub.yml
